source "https://rubygems.org"

gem 'activesupport'
gem 'awesome_print'
gem 'redis'

# Расспаралеливание в потоки (для Redis соединения). Не путать с кластеризацией Redis!
gem 'connection_pool', '~> 2.2', '>= 2.2.5'
