---
version: "3.8"

services:
  pg:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?Пользователь postgres не установлен, смотри файл .env}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?Пароль postgres не установлен, смотри файл .env}
    ports:
      - 49432:5432
    restart: unless-stopped
