DROP TABLE IF EXISTS a;
CREATE TABLE a (a_id SERIAL PRIMARY KEY, name VARCHAR(255));

INSERT INTO a VALUES (DEFAULT, '1'), (DEFAULT, '2');
SELECT * FROM a;
BEGIN;
UPDATE a SET a_id = 3 WHERE a_id = 2;
UPDATE a SET a_id = 2 WHERE a_id = 1;
COMMIT;
SELECT * FROM a;
