#!/bin/bash

function echoc {

  # OLD_CD=$(pwd)
  # cd $(dirname $BASH_SOURCE)
  # . colorize
  # cd $OLD_CD

  # Объявления hash-подобного массива
  declare -A COLORS
  COLORS=(
    ['style_default']='\033[0m'

    ['red']='\033[31m'
    ['green']='\033[32m'
    ['blue']='\033[36m'
    ['yellow']='\033[33m'

    ['bold']='\033[1m'
  )
  echo -en ${COLORS[$2]}
  echo -e $1
  echo -en ${COLORS[style_default]}
}
