DROP TABLE IF EXISTS `a`;
DROP TABLE IF EXISTS `b`;

CREATE TABLE `a` (
  `a_id` INT UNSIGNED NOT NULL,
  `a_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`a_id`)
);

CREATE TABLE `b` (
  `b_id` INT UNSIGNED NOT NULL,
  `b_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`b_id`)
);
