.\" Руководство к zaccesses.
.TH man 8 "30 Августа 2018" "1.0" "zaccesses man page"
.SH НАЗВАНИЕ
zaccesses — доступы проектов и ssh конфигурация
.SH СИНТАКСИС
zaccesses [<options>] <command> [<args>]
.SH ОПИСАНИЕ
Втягивание/заталкивание доступов к проектам или ssh конфигурации на удалённое хранилище используя webdav протокол.
.SH ПРИМЕРЫ
zaccesses <projects_group>  — втянуть доступы группы проектов.
zaccesses sshconfig         — втянуть конфигурацию ssh.
.SH ОПЦИИ
.TP
\fB\-o\fP | \fB\-\-open\fP
Откроект \fIлокальные\fP доступы/конфигурацию.
.TP
\fB\-s\fP | \fB\-\-save\fP
Втолкнёт \fIлокальные\fP доступы/конфигурацию на удалённое хранилище.
.SH БАГИ
Нет известных багов.
.SH АВТОР
Максим Златов
